package com.manaKhata.expense;

public enum ExpenseCategory {
    FOOD, GROCERIES, PETROL, TRAVEL, RENT, ELECTRICITY,
    INTERNET, MEDICAL, SHOPPING, EDUCATION, ENTERTAINMENT,
    INVESTMENT, SAVINGS, REPAIRS, MAINTENANCE, EMERGENCY,
    CLOTHING, PERSONAL_CARE, VEHICLE, UTILITIES, SUBSCRIPTION,
    OTHER
}
